import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { EQUIPMENT_CATALOG } from "@/src/catalog";

const apiUrl=process.env.AMBI_API_URL??"https://app.ambiguous.ai";const token=process.env.FADS_CLAW_TOKEN??process.env.AMBI_API_TOKEN;if(!token)throw new Error("FADS_CLAW_TOKEN is required");
async function call<T>(path:string,method="GET",body?:unknown):Promise<T>{const response=await fetch(`${apiUrl}${path}`,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","API-Version":"1"},body:body?JSON.stringify(body):undefined});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(`${response.status}: ${data.error??JSON.stringify(data)}`);return data;}
const projects=await call<{data:Array<{id:string;name:string}>}>("/api/projects?limit=100");let project=projects.data.find((item)=>item.name==="Road Incidents");if(!project)project=await call<{id:string;name:string}>("/api/projects","POST",{name:"Road Incidents",description:"FADS demo incident operations",icon:"road",color:"#174F37",visibility:"workspace"});
const desired=[
  ["Reported","triage","#6B7280"],["Assessing","in_progress","#405EF2"],["Needs Review","blocked","#E76F3D"],["Awaiting Approval","in_review","#D59E0B"],["Scheduled","in_progress","#7357D9"],["In Progress","in_progress","#174F37"],["Resolved","done","#3A8F5C"],["Blocked","blocked","#B23A31"],["Cancelled","cancelled","#777777"],
] as const;
const statuses=await call<{data:Array<{id:string;name:string}>}>(`/api/tasks/statuses?limit=100`);const statusIds:Record<string,string>={};for(const [name,category,color] of desired){let status=statuses.data.find((item)=>item.name===name);if(!status)status=await call<{id:string;name:string}>("/api/tasks/statuses","POST",{name,category,color});statusIds[name.toLowerCase().replaceAll(" ","_")]=status.id;}
const calendars=await call<{data:Array<{id:string;name:string}>}>("/api/calendars");let calendar=calendars.data.find((item)=>item.name==="FADS Operations");if(!calendar)calendar=await call<{id:string;name:string}>("/api/calendars","POST",{name:"FADS Operations",color:"#174F37",timezone:"America/Los_Angeles",working_hours:{sun:["08:00","18:00"],mon:["08:00","18:00"],tue:["08:00","18:00"],wed:["08:00","18:00"],thu:["08:00","18:00"],fri:["08:00","18:00"],sat:["08:00","18:00"]}});
const resourceResponse=await call<{resources?:Array<{id:string;name:string}>;data?:Array<{id:string;name:string}>}>("/api/calendars/resources");const resources=resourceResponse.resources??resourceResponse.data??[];const resourceIds:Record<string,string>={};for(const item of EQUIPMENT_CATALOG){let resource=resources.find((row)=>row.name===item.name);if(!resource)resource=await call<{id:string;name:string}>("/api/calendars/resources","POST",{name:item.name,type:"equipment",description:item.description,capacity:1,calendar_id:calendar.id});resourceIds[item.key]=resource.id;}
const output={projectId:project.id,calendarId:calendar.id,statusIds:{reported:statusIds.reported,assessing:statusIds.assessing,needs_review:statusIds.needs_review,awaiting_approval:statusIds.awaiting_approval,scheduled:statusIds.scheduled,in_progress:statusIds.in_progress,resolved:statusIds.resolved,blocked:statusIds.blocked,cancelled:statusIds.cancelled},resourceIds};await mkdir(join(process.cwd(),"data"),{recursive:true});await writeFile(join(process.cwd(),"data","ambiguous-resources.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));
